name = "roll-dorado-casino-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-casino.com.gr"
HMAC_KEY = "9f8d48fe5385efd73c82b6cfdae030a6aa619b52eed67eb717c9d5e106cb6123"
COOKIE_NAME = "244"
PLAY_PATH = "play"
BUTTON_ID = "p9a3afa7de6fbb02f75e6235f3578b3e4"
GATE_SALT = "c31fb4f0642a1b0e"
